"""Enterprise Identity Trust Framework constants (Phase 21.6)."""

TRUSTED_DEVICE_COOKIE = "vb_trusted_device"
DEVICE_TOKEN_BYTES = 32

RISK_ALLOW = "ALLOW"
RISK_REQUIRE_OTP = "REQUIRE_OTP"
RISK_REQUIRE_BIOMETRIC = "REQUIRE_BIOMETRIC"
RISK_BLOCK = "BLOCK"

DEFAULT_TRUSTED_DEVICE_EXPIRATION_DAYS = 90
DEFAULT_UNIVERSITY_DEVICE_EXPIRATION_DAYS = 180
DEFAULT_PERSONAL_DEVICE_EXPIRATION_DAYS = 60
DEFAULT_MAX_TRUSTED_DEVICES = 5

HIGH_RISK_THRESHOLD = 70.0
BLOCK_RISK_THRESHOLD = 95.0
MAX_DEVICE_RISK_SCORE = 100.0

FINGERPRINT_MISMATCH_PENALTY = 25.0
MISSING_TOKEN_PENALTY = 40.0
INVALID_TOKEN_PENALTY = 50.0
COUNTRY_CHANGE_PENALTY = 35.0
FAILED_LOGIN_PENALTY = 20.0
NEW_DEVICE_PENALTY = 30.0
EXPIRED_TRUST_PENALTY = 45.0
UNKNOWN_BROWSER_PENALTY = 15.0
IMPOSSIBLE_TRAVEL_PENALTY = 80.0

BIOMETRIC_RECENT_HOURS = 24
LOW_TRUST_RISK_THRESHOLD = 50.0
HIGH_TRUST_RISK_THRESHOLD = 30.0

AUTH_METHOD_TRUSTED = "trusted_device"
AUTH_METHOD_BIOMETRIC = "biometric"
AUTH_METHOD_OTP = "otp"


class TrustLevel:
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    REVOKED = "REVOKED"

    CHOICES = (
        (HIGH, "High"),
        (MEDIUM, "Medium"),
        (LOW, "Low"),
        (REVOKED, "Revoked"),
    )


class DeviceType:
    UNIVERSITY_MANAGED = "university_managed"
    PERSONAL = "personal"

    CHOICES = (
        (UNIVERSITY_MANAGED, "University Managed"),
        (PERSONAL, "Personal Device"),
    )
