# Generated by Django 5.2.15 on 2026-06-27 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('schedule_cron', models.CharField(blank=True, max_length=80)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_backup_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_changed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flag_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_feature_flag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('institution_name', models.CharField(default='Takoradi Technical University', max_length=200)),
                ('short_name', models.CharField(default='TTU', max_length=40)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution/logos/')),
                ('logo_url', models.URLField(blank=True)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='institution/favicons/')),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#1E5F46', max_length=7)),
                ('secondary_color', models.CharField(default='#334155', max_length=7)),
                ('academic_year', models.CharField(blank=True, default='2024/2025', max_length=20)),
                ('campus', models.CharField(blank=True, default='Main Campus', max_length=120)),
                ('contact_email', models.EmailField(blank=True, default='info@ttu.edu.gh', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('election_office_name', models.CharField(blank=True, default='Electoral Commission Office', max_length=160)),
                ('election_office_email', models.EmailField(blank=True, default='elections@ttu.edu.gh', max_length=254)),
                ('election_office_phone', models.CharField(blank=True, max_length=30)),
                ('footer_text', models.TextField(blank=True)),
                ('public_urls', models.JSONField(blank=True, default=dict)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'institution profile',
                'db_table': 'system_institution_profile',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('read_only_mode', models.BooleanField(default=False)),
                ('emergency_stop_voting', models.BooleanField(default=False)),
                ('emergency_stop_results', models.BooleanField(default=False)),
                ('disable_login', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='VoteBridge is undergoing scheduled maintenance.')),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_maintenance_state',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('value', models.JSONField(default=dict)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_setting',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SettingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('setting_key', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(max_length=40)),
                ('old_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField()),
                ('change_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_revisions', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='system.systemsetting')),
            ],
            options={
                'db_table': 'system_setting_revision',
                'ordering': ['-created_at'],
            },
        ),
    ]
