# Generated by Django 5.2.15 on 2026-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_seed_system_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionprofile',
            name='primary_color',
            field=models.CharField(default='#1E3A6E', max_length=7),
        ),
    ]
