# Generated by Django 5.2.15 on 2026-06-25 13:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('provider_type', models.CharField(choices=[('arkesel_sms', 'Arkesel SMS'), ('smtp_email', 'SMTP Email')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('connection_status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('error', 'Error')], default='unknown', max_length=20)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_provider',
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App'), ('multi', 'Multi-Channel')], db_index=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('sms_body', models.TextField(blank=True)),
                ('in_app_title', models.CharField(blank=True, max_length=255)),
                ('in_app_body', models.TextField(blank=True)),
                ('placeholders', models.JSONField(blank=True, default=list, help_text='List of supported placeholder keys, e.g. first_name, election_name.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications_template',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('recipient', models.CharField(db_index=True, max_length=255)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App')], db_index=True, max_length=20)),
                ('template_code', models.CharField(blank=True, db_index=True, max_length=80)),
                ('provider_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_snapshot', models.TextField(blank=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retries', models.PositiveSmallIntegerField(default=3)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='notifications.communicationprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notifications_delivery_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=60)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delivery_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_app_notifications', to='notifications.deliverylog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_in_app',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'is_deleted'], name='notificatio_user_id_9921cb_idx'), models.Index(fields=['user', 'is_archived', 'is_deleted'], name='notificatio_user_id_689d65_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['status', 'channel'], name='notificatio_status_a8fff0_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverylog',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificatio_status_5d5bc6_idx'),
        ),
    ]
