# Generated by Django 5.2.15 on 2026-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_moolre_sms_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationprovider',
            name='provider_type',
            field=models.CharField(choices=[('arkesel_sms', 'Arkesel SMS'), ('moolre_sms', 'Moolre SMS'), ('smtp_email', 'SMTP Email')], db_index=True, max_length=30),
        ),
    ]
