# Generated by Django 5.2.15 on 2026-06-25 14:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('msisdn', models.CharField(db_index=True, max_length=20)),
                ('service_code', models.CharField(blank=True, max_length=40)),
                ('network', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='active', max_length=20)),
                ('current_step', models.CharField(db_index=True, default='WELCOME', max_length=60)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('completed_vote', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ussd_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='USSDRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('carrier_session_id', models.CharField(db_index=True, max_length=120)),
                ('msisdn', models.CharField(db_index=True, max_length=20)),
                ('raw_input', models.TextField(blank=True)),
                ('parsed_inputs', models.JSONField(blank=True, default=list)),
                ('step_before', models.CharField(blank=True, max_length=60)),
                ('step_after', models.CharField(blank=True, max_length=60)),
                ('response_message', models.TextField(blank=True)),
                ('continue_session', models.BooleanField(default=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout'), ('invalid', 'Invalid')], db_index=True, default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='ussd.ussdsession')),
            ],
            options={
                'db_table': 'ussd_request_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['status', 'last_activity_at'], name='ussd_sessio_status_6b8a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdsession',
            index=models.Index(fields=['msisdn', 'status'], name='ussd_sessio_msisdn_626498_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdrequestlog',
            index=models.Index(fields=['outcome', 'created_at'], name='ussd_reques_outcome_d18fdc_idx'),
        ),
        migrations.AddIndex(
            model_name='ussdrequestlog',
            index=models.Index(fields=['msisdn', 'created_at'], name='ussd_reques_msisdn_98696a_idx'),
        ),
    ]
