# Generated by Django 5.2.15 on 2026-06-25 12:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0003_position_votereligibility'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_uuid', models.UUIDField(blank=True, null=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('current_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_actions', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_records', to='elections.election')),
            ],
            options={
                'db_table': 'strongroom_custody_record',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ElectionSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('election_seal_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('verification_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('ballot_seals_digest', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sealed', 'Sealed'), ('locked', 'Locked')], db_index=True, default='pending', max_length=20)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='election_seal', to='elections.election')),
                ('election_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='election_seal', to='results.electionresult')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_seals_locked', to=settings.AUTH_USER_MODEL)),
                ('sealed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_seals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strongroom_election_seal',
            },
        ),
        migrations.CreateModel(
            name='IntegrityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('verification_type', models.CharField(choices=[('full', 'Full'), ('public', 'Public'), ('strongroom', 'Strongroom')], max_length=20)),
                ('is_valid', models.BooleanField(default=False)),
                ('integrity_score', models.PositiveSmallIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('verification_hash_used', models.CharField(blank=True, max_length=128)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_verifications', to='elections.election')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strongroom_integrity_verification',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='BallotSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('svt_id', models.UUIDField(db_index=True)),
                ('vote_references', models.JSONField(default=list, help_text='Ordered list of vote_id UUIDs referencing voting_vote records.')),
                ('seal_hash', models.CharField(db_index=True, max_length=128)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('sealed', 'Sealed'), ('verified', 'Verified'), ('compromised', 'Compromised')], db_index=True, default='sealed', max_length=20)),
                ('sealed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot_seals', to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot_seals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'strongroom_ballot_seal',
                'ordering': ['-sealed_at'],
                'constraints': [models.UniqueConstraint(fields=('election', 'user', 'svt_id'), name='strongroom_unique_ballot_seal_per_svt')],
            },
        ),
    ]
