import { createRouter, createWebHistory } from "vue-router";
import DashboardLayout from "@/layouts/DashboardLayout.vue";
import AuthLayout from "@/layouts/AuthLayout.vue";
import ElectionLayout from "@/layouts/ElectionLayout.vue";
import PublicLayout from "@/layouts/PublicLayout.vue";
import VerificationLayout from "@/layouts/VerificationLayout.vue";

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: "/auth",
      component: AuthLayout,
      meta: { guest: true },
      children: [
        {
          path: "login",
          name: "auth-login",
          component: () => import("@/views/auth/LoginView.vue"),
          meta: { title: "Sign in" },
        },
        {
          path: "otp",
          name: "auth-otp",
          component: () => import("@/views/auth/OTPVerificationView.vue"),
          meta: { title: "Verify code", requiresOtp: true, guest: true },
        },
        {
          path: "biometric-verify",
          name: "auth-biometric-verify",
          component: () => import("@/views/biometrics/BiometricVerifyView.vue"),
          meta: { title: "Identity verification", requiresBiometric: true, guest: true },
        },
        {
          path: "info/election-period",
          name: "auth-info-election-period",
          component: () => import("@/views/auth/info/AuthInfoPageView.vue"),
          meta: { title: "Election period", guest: true, infoPage: true, infoSlug: "election-period" },
        },
        {
          path: "info/voting-instructions",
          name: "auth-info-voting-instructions",
          component: () => import("@/views/auth/info/AuthInfoPageView.vue"),
          meta: { title: "Voting instructions", guest: true, infoPage: true, infoSlug: "voting-instructions" },
        },
        {
          path: "info/security",
          name: "auth-info-security",
          component: () => import("@/views/auth/info/AuthInfoPageView.vue"),
          meta: { title: "Security information", guest: true, infoPage: true, infoSlug: "security" },
        },
        {
          path: "info/help",
          name: "auth-info-help",
          component: () => import("@/views/auth/info/AuthInfoPageView.vue"),
          meta: { title: "Help & FAQ", guest: true, infoPage: true, infoSlug: "help" },
        },
      ],
    },
    {
      path: "/",
      component: DashboardLayout,
      meta: { requiresAuth: true },
      children: [
        {
          path: "",
          name: "home",
          component: () => import("@/views/dashboard/DashboardHubView.vue"),
          meta: { title: "Overview" },
        },
        {
          path: "dashboard/student",
          name: "dashboard-student",
          component: () => import("@/views/dashboard/StudentDashboardView.vue"),
          meta: { title: "Student Dashboard", roles: ["student", "candidate"] },
        },
        {
          path: "dashboard/admin",
          name: "dashboard-admin",
          component: () => import("@/views/dashboard/AdminDashboardView.vue"),
          meta: { title: "Admin Dashboard", roles: ["admin"] },
        },
        {
          path: "dashboard/super-admin",
          name: "dashboard-super-admin",
          component: () => import("@/views/dashboard/SuperAdminDashboardView.vue"),
          meta: { title: "Super Admin Dashboard", roles: ["super_admin"] },
        },
        {
          path: "profile",
          name: "profile",
          component: () => import("@/views/auth/ProfileView.vue"),
          meta: { title: "Profile" },
        },
        {
          path: "forbidden",
          name: "forbidden",
          component: () => import("@/views/errors/ForbiddenView.vue"),
          meta: { title: "Access Denied" },
        },
        {
          path: "error",
          name: "server-error",
          component: () => import("@/views/errors/ServerErrorView.vue"),
          meta: { title: "Server Error" },
        },
        {
          path: "elections/create",
          name: "election-create",
          component: () => import("@/views/elections/ElectionCreateView.vue"),
          meta: { title: "Create Election", roles: ["admin", "super_admin"] },
        },
        {
          path: "election-management/candidates",
          name: "election-management-candidates",
          component: () => import("@/views/election-management/ElectionCandidatesView.vue"),
          meta: { title: "Candidates", roles: ["admin", "super_admin"] },
        },
        {
          path: "election-management/positions",
          name: "election-management-positions",
          component: () => import("@/views/election-management/ElectionPositionsView.vue"),
          meta: { title: "Positions", roles: ["admin", "super_admin"] },
        },
        {
          path: "election-management/eligibility",
          name: "election-management-eligibility",
          component: () => import("@/views/election-management/ElectionEligibilityView.vue"),
          meta: { title: "Voter Eligibility", roles: ["admin", "super_admin"] },
        },
        {
          path: "elections",
          name: "elections",
          component: () => import("@/views/elections/ElectionListView.vue"),
          meta: { title: "Elections" },
        },
        {
          path: "security",
          name: "security",
          component: () => import("@/views/security/SecurityView.vue"),
          meta: { title: "Security Center" },
        },
        {
          path: "security/trusted-devices",
          name: "security-trusted-devices",
          component: () => import("@/views/security/TrustedDevicesView.vue"),
          meta: { title: "Trusted Devices", roles: ["admin", "super_admin"] },
        },
        {
          path: "fraud",
          name: "fraud",
          component: () => import("@/views/fraud/FraudView.vue"),
          meta: { title: "Fraud Dashboard" },
        },
        {
          path: "results",
          name: "results",
          component: () => import("@/views/results/ResultsHubView.vue"),
          meta: { title: "Results" },
        },
        {
          path: "results/certification",
          name: "results-certification",
          component: () => import("@/views/results/CertificationQueueView.vue"),
          meta: { title: "Certification Queue", roles: ["super_admin"] },
        },
        {
          path: "results/publication",
          name: "results-publication",
          component: () => import("@/views/results/PublicationCenterView.vue"),
          meta: { title: "Publication Center", roles: ["super_admin"] },
        },
        {
          path: "results/archive",
          name: "results-archive",
          component: () => import("@/views/results/ArchiveManagerView.vue"),
          meta: { title: "Archive Manager", roles: ["super_admin"] },
        },
        {
          path: "results/:electionUuid",
          name: "result-detail",
          component: () => import("@/views/results/ResultDetailView.vue"),
          meta: { title: "Election Results" },
        },
        {
          path: "strongroom",
          component: () => import("@/layouts/StrongroomWorkspaceLayout.vue"),
          meta: { title: "Strong Room", roles: ["admin", "super_admin"] },
          children: [
            {
              path: "",
              name: "strongroom",
              component: () => import("@/views/strongroom/StrongroomDashboardView.vue"),
              meta: { title: "Vote Integrity" },
            },
            {
              path: "certification",
              name: "strongroom-certification",
              component: () => import("@/views/results/CertificationQueueView.vue"),
              meta: { title: "Certification", roles: ["super_admin"] },
            },
            {
              path: "audit",
              name: "strongroom-audit",
              component: () => import("@/views/platform/PlatformLogsView.vue"),
              meta: { title: "Audit Trail" },
            },
            {
              path: "fraud",
              name: "strongroom-fraud",
              component: () => import("@/views/fraud/FraudView.vue"),
              meta: { title: "Fraud Investigation" },
            },
            {
              path: "custody",
              name: "strongroom-custody",
              component: () => import("@/views/strongroom/StrongroomCustodyHubView.vue"),
              meta: { title: "Chain of Custody" },
            },
            {
              path: "identity",
              name: "strongroom-identity",
              component: () => import("@/views/biometrics/BiometricHistoryView.vue"),
              meta: { title: "Identity Assurance" },
            },
            {
              path: "trusted-devices",
              name: "strongroom-trusted-devices",
              component: () => import("@/views/security/TrustedDevicesView.vue"),
              meta: { title: "Trusted Devices" },
            },
            {
              path: "security",
              name: "strongroom-security",
              component: () => import("@/views/security/SecurityView.vue"),
              meta: { title: "Security Timeline" },
            },
            {
              path: "export",
              name: "strongroom-export",
              component: () => import("@/views/strongroom/StrongroomEvidenceExportView.vue"),
              meta: { title: "Evidence Export" },
            },
          ],
        },
        {
          path: "strongroom/:electionUuid",
          name: "strongroom-election",
          component: () => import("@/views/strongroom/StrongroomElectionView.vue"),
          meta: { title: "Election Strongroom", roles: ["admin", "super_admin"] },
        },
        {
          path: "communications",
          name: "communications",
          component: () => import("@/views/communications/CommunicationDashboardView.vue"),
          meta: { title: "Communication Center", roles: ["admin", "super_admin"] },
        },
        {
          path: "communications/logs",
          redirect: (to) => ({ name: "platform-logs", query: { ...to.query, tab: "communications" } }),
        },
        {
          path: "communications/providers",
          name: "communications-providers",
          component: () => import("@/views/communications/ProvidersView.vue"),
          meta: { title: "Providers", roles: ["admin", "super_admin"] },
        },
        {
          path: "communications/templates",
          name: "communications-templates",
          component: () => import("@/views/communications/TemplatesView.vue"),
          meta: { title: "Templates", roles: ["admin", "super_admin"] },
        },
        {
          path: "communications/test",
          name: "communications-test",
          component: () => import("@/views/communications/TestCenterView.vue"),
          meta: { title: "Test Center", roles: ["admin", "super_admin"] },
        },
        {
          path: "communications/queue",
          name: "communications-queue",
          component: () => import("@/views/communications/QueueMonitorView.vue"),
          meta: { title: "Queue Monitor", roles: ["admin", "super_admin"] },
        },
        {
          path: "notifications",
          name: "notifications",
          component: () => import("@/views/communications/NotificationCenterView.vue"),
          meta: { title: "Notification Center" },
        },
        {
          path: "ussd",
          name: "ussd",
          component: () => import("@/views/ussd/UssdDashboardView.vue"),
          meta: { title: "USSD Management", roles: ["admin", "super_admin"] },
        },
        {
          path: "ussd/sessions",
          name: "ussd-sessions",
          component: () => import("@/views/ussd/SessionMonitorView.vue"),
          meta: { title: "USSD Sessions", roles: ["admin", "super_admin"] },
        },
        {
          path: "ussd/logs",
          redirect: (to) => ({ name: "platform-logs", query: { ...to.query, tab: "ussd" } }),
        },
        {
          path: "operations",
          name: "operations",
          component: () => import("@/views/operations/OperationsOverviewView.vue"),
          meta: { title: "Operations Center", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/activity",
          name: "operations-activity",
          component: () => import("@/views/operations/OperationsActivityView.vue"),
          meta: { title: "Live Activity", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/health",
          name: "operations-health",
          component: () => import("@/views/operations/OperationsHealthView.vue"),
          meta: { title: "System Health", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/infrastructure",
          name: "operations-infrastructure",
          component: () => import("@/views/operations/OperationsInfrastructureView.vue"),
          meta: { title: "Infrastructure", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/elections",
          name: "operations-elections",
          component: () => import("@/views/operations/OperationsElectionMonitorView.vue"),
          meta: { title: "Election Monitor", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/communications",
          name: "operations-communications",
          component: () => import("@/views/operations/OperationsCommunicationsView.vue"),
          meta: { title: "Operations Communications", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/sessions",
          name: "operations-sessions",
          component: () => import("@/views/operations/OperationsSessionsView.vue"),
          meta: { title: "Users & Sessions", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/queues",
          name: "operations-queues",
          component: () => import("@/views/operations/OperationsQueuesView.vue"),
          meta: { title: "Operations Queues", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/performance",
          name: "operations-performance",
          component: () => import("@/views/operations/OperationsPerformanceView.vue"),
          meta: { title: "Performance", roles: ["admin", "super_admin"] },
        },
        {
          path: "operations/logs",
          redirect: (to) => ({ name: "platform-logs", query: { ...to.query, tab: "operations" } }),
        },
        {
          path: "platform/logs",
          name: "platform-logs",
          component: () => import("@/views/platform/PlatformLogsView.vue"),
          meta: { title: "Platform Logs", roles: ["admin", "super_admin"] },
        },
        {
          path: "system-control",
          redirect: { name: "settings" },
        },
        {
          path: "settings",
          name: "settings",
          component: () => import("@/views/system-control/SystemControlOverviewView.vue"),
          meta: { title: "Settings", roles: ["super_admin"] },
        },
        {
          path: "settings/institution",
          name: "settings-institution",
          component: () => import("@/views/system-control/SystemInstitutionView.vue"),
          meta: { title: "Institution Settings", roles: ["super_admin"] },
        },
        {
          path: "settings/branding",
          name: "settings-branding",
          component: () => import("@/views/system-control/SystemBrandingView.vue"),
          meta: { title: "Branding", roles: ["super_admin"] },
        },
        {
          path: "settings/election-policies",
          name: "settings-election-policies",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "election_policies", title: "Election Policies" },
          meta: { title: "Election Policies", roles: ["super_admin"] },
        },
        {
          path: "settings/authentication",
          name: "settings-authentication",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "authentication", title: "Authentication", sensitive: true },
          meta: { title: "Authentication", roles: ["super_admin"] },
        },
        {
          path: "settings/identity-assurance",
          name: "settings-identity-assurance",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "identity_assurance", title: "Identity Assurance", sensitive: true },
          meta: { title: "Identity Assurance", roles: ["super_admin"] },
        },
        {
          path: "settings/security",
          name: "settings-security",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "security", title: "Security Policies", sensitive: true },
          meta: { title: "Security Policies", roles: ["super_admin"] },
        },
        {
          path: "settings/api",
          name: "settings-api",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "api", title: "API & Integrations" },
          meta: { title: "API & Integrations", roles: ["super_admin"] },
        },
        {
          path: "settings/audit",
          name: "settings-audit",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "audit", title: "Audit Settings" },
          meta: { title: "Audit Settings", roles: ["super_admin"] },
        },
        {
          path: "settings/notifications",
          name: "settings-notifications",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "notifications", title: "Notification Settings" },
          meta: { title: "Notification Settings", roles: ["super_admin"] },
        },
        {
          path: "settings/ussd",
          name: "settings-ussd",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "ussd", title: "USSD Configuration" },
          meta: { title: "USSD Configuration", roles: ["super_admin"] },
        },
        {
          path: "settings/providers",
          name: "settings-providers",
          component: () => import("@/views/system-control/SystemProvidersView.vue"),
          meta: { title: "Communication Providers", roles: ["super_admin"] },
        },
        {
          path: "settings/voting-channels",
          name: "settings-voting-channels",
          component: () => import("@/views/settings/VotingChannelsSettingsView.vue"),
          meta: { title: "Voting Channels", roles: ["super_admin"] },
        },
        {
          path: "settings/feature-flags",
          name: "settings-feature-flags",
          component: () => import("@/views/system-control/SystemFeatureFlagsView.vue"),
          meta: { title: "Feature Flags", roles: ["super_admin"] },
        },
        {
          path: "settings/maintenance",
          name: "settings-maintenance",
          component: () => import("@/views/system-control/SystemMaintenanceView.vue"),
          meta: { title: "System Maintenance", roles: ["super_admin"] },
        },
        {
          path: "settings/backup",
          name: "settings-backup",
          component: () => import("@/views/system-control/SystemBackupView.vue"),
          meta: { title: "Backup & Recovery", roles: ["super_admin"] },
        },
        {
          path: "settings/system",
          name: "settings-system",
          component: () => import("@/views/settings/SettingsSystemHubView.vue"),
          meta: { title: "System Configuration", roles: ["super_admin"] },
        },
        {
          path: "settings/runtime",
          name: "settings-runtime",
          component: () => import("@/views/system-control/SystemRuntimeView.vue"),
          meta: { title: "Runtime Configuration", roles: ["super_admin"] },
        },
        {
          path: "settings/environment",
          name: "settings-environment",
          component: () => import("@/views/system-control/SystemEnvironmentView.vue"),
          meta: { title: "Environment", roles: ["super_admin"] },
        },
        {
          path: "settings/storage",
          name: "settings-storage",
          component: () => import("@/views/system-control/SystemStorageView.vue"),
          meta: { title: "Storage", roles: ["super_admin"] },
        },
        {
          path: "system-control/institution",
          name: "system-control-institution",
          component: () => import("@/views/system-control/SystemInstitutionView.vue"),
          meta: { title: "Institution Settings", roles: ["super_admin"] },
        },
        {
          path: "system-control/branding",
          name: "system-control-branding",
          component: () => import("@/views/system-control/SystemBrandingView.vue"),
          meta: { title: "Branding", roles: ["super_admin"] },
        },
        {
          path: "system-control/election-policies",
          name: "system-control-election-policies",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "election_policies", title: "Election Policies" },
          meta: { title: "Election Policies", roles: ["super_admin"] },
        },
        {
          path: "system-control/authentication",
          name: "system-control-authentication",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "authentication", title: "Authentication", sensitive: true },
          meta: { title: "Authentication", roles: ["super_admin"] },
        },
        {
          path: "system-control/identity-assurance",
          name: "system-control-identity-assurance",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "identity_assurance", title: "Identity Assurance", sensitive: true },
          meta: { title: "Identity Assurance", roles: ["super_admin"] },
        },
        {
          path: "biometrics/enroll",
          name: "biometrics-enroll",
          component: () => import("@/views/biometrics/BiometricEnrollView.vue"),
          meta: { title: "Biometric Enrollment", roles: ["super_admin"] },
        },
        {
          path: "biometrics/history",
          name: "biometrics-history",
          component: () => import("@/views/biometrics/BiometricHistoryView.vue"),
          meta: { title: "Biometric History", roles: ["admin", "super_admin"] },
        },
        {
          path: "system-control/security",
          name: "system-control-security",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "security", title: "Security", sensitive: true },
          meta: { title: "Security", roles: ["super_admin"] },
        },
        {
          path: "system-control/api",
          name: "system-control-api",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "api", title: "API Management" },
          meta: { title: "API Management", roles: ["super_admin"] },
        },
        {
          path: "system-control/audit",
          name: "system-control-audit",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "audit", title: "Audit Settings" },
          meta: { title: "Audit Settings", roles: ["super_admin"] },
        },
        {
          path: "system-control/notifications",
          name: "system-control-notifications",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "notifications", title: "Notification Settings" },
          meta: { title: "Notification Settings", roles: ["super_admin"] },
        },
        {
          path: "system-control/ussd",
          name: "system-control-ussd",
          component: () => import("@/views/system-control/SystemCategorySettingsView.vue"),
          props: { category: "ussd", title: "USSD Configuration" },
          meta: { title: "USSD", roles: ["super_admin"] },
        },
        {
          path: "system-control/providers",
          name: "system-control-providers",
          component: () => import("@/views/system-control/SystemProvidersView.vue"),
          meta: { title: "Communication Providers", roles: ["super_admin"] },
        },
        {
          path: "system-control/sms",
          name: "system-control-sms",
          component: () => import("@/views/system-control/SystemProvidersView.vue"),
          props: { providerType: "arkesel_sms", title: "SMS Providers" },
          meta: { title: "SMS", roles: ["super_admin"] },
        },
        {
          path: "system-control/email",
          name: "system-control-email",
          component: () => import("@/views/system-control/SystemProvidersView.vue"),
          props: { providerType: "smtp_email", title: "Email Providers" },
          meta: { title: "Email", roles: ["super_admin"] },
        },
        {
          path: "system-control/feature-flags",
          name: "system-control-feature-flags",
          component: () => import("@/views/system-control/SystemFeatureFlagsView.vue"),
          meta: { title: "Feature Flags", roles: ["super_admin"] },
        },
        {
          path: "system-control/maintenance",
          name: "system-control-maintenance",
          component: () => import("@/views/system-control/SystemMaintenanceView.vue"),
          meta: { title: "System Maintenance", roles: ["super_admin"] },
        },
        {
          path: "system-control/storage",
          name: "system-control-storage",
          component: () => import("@/views/system-control/SystemStorageView.vue"),
          meta: { title: "Storage", roles: ["super_admin"] },
        },
        {
          path: "system-control/backup",
          name: "system-control-backup",
          component: () => import("@/views/system-control/SystemBackupView.vue"),
          meta: { title: "Backup & Recovery", roles: ["super_admin"] },
        },
        {
          path: "system-control/environment",
          name: "system-control-environment",
          component: () => import("@/views/system-control/SystemEnvironmentView.vue"),
          meta: { title: "Environment", roles: ["super_admin"] },
        },
        {
          path: "system-control/runtime",
          name: "system-control-runtime",
          component: () => import("@/views/system-control/SystemRuntimeView.vue"),
          meta: { title: "Runtime Configuration", roles: ["super_admin"] },
        },
        {
          path: "system-control/license",
          name: "system-control-license",
          component: () => import("@/views/system-control/SystemLicenseView.vue"),
          meta: { title: "License", roles: ["super_admin"] },
        },
        {
          path: "system-control/about",
          name: "system-control-about",
          component: () => import("@/views/system-control/SystemAboutView.vue"),
          meta: { title: "About", roles: ["super_admin"] },
        },
        {
          path: "analytics",
          redirect: { name: "reports" },
        },
        {
          path: "reports",
          name: "reports",
          component: () => import("@/views/analytics/AnalyticsOverviewView.vue"),
          meta: { title: "Reports", roles: ["admin", "super_admin"] },
        },
        {
          path: "reports/participation",
          name: "reports-participation",
          component: () => import("@/views/analytics/AnalyticsParticipationView.vue"),
          meta: { title: "Participation", roles: ["admin", "super_admin"] },
        },
        {
          path: "reports/turnout",
          name: "reports-turnout",
          component: () => import("@/views/analytics/AnalyticsElectionsView.vue"),
          meta: { title: "Turnout", roles: ["admin", "super_admin"] },
        },
        {
          path: "reports/results",
          name: "reports-results",
          component: () => import("@/views/analytics/AnalyticsElectionsView.vue"),
          meta: { title: "Results Reports", roles: ["admin", "super_admin"] },
        },
        {
          path: "reports/historical",
          name: "reports-historical",
          component: () => import("@/views/analytics/AnalyticsHistoricalView.vue"),
          meta: { title: "Historical Trends", roles: ["admin", "super_admin"] },
        },
        {
          path: "reports/export",
          name: "reports-export",
          component: () => import("@/views/analytics/AnalyticsReportsView.vue"),
          meta: { title: "Export Reports", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/elections",
          name: "analytics-elections",
          component: () => import("@/views/analytics/AnalyticsElectionsView.vue"),
          meta: { title: "Election Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/participation",
          name: "analytics-participation",
          component: () => import("@/views/analytics/AnalyticsParticipationView.vue"),
          meta: { title: "Participation Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/students",
          name: "analytics-students",
          component: () => import("@/views/analytics/AnalyticsStudentsView.vue"),
          meta: { title: "Student Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/departments",
          name: "analytics-departments",
          component: () => import("@/views/analytics/AnalyticsDepartmentsView.vue"),
          meta: { title: "Department Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/faculties",
          name: "analytics-faculties",
          component: () => import("@/views/analytics/AnalyticsFacultiesView.vue"),
          meta: { title: "Faculty Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/programmes",
          name: "analytics-programmes",
          component: () => import("@/views/analytics/AnalyticsProgrammesView.vue"),
          meta: { title: "Programme Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/security",
          name: "analytics-security",
          component: () => import("@/views/analytics/AnalyticsSecurityView.vue"),
          meta: { title: "Security Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/fraud",
          name: "analytics-fraud",
          component: () => import("@/views/analytics/AnalyticsFraudView.vue"),
          meta: { title: "Fraud Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/operations",
          name: "analytics-operations",
          component: () => import("@/views/analytics/AnalyticsOperationsView.vue"),
          meta: { title: "Operations Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/communications",
          name: "analytics-communications",
          component: () => import("@/views/analytics/AnalyticsCommunicationsView.vue"),
          meta: { title: "Communication Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/ussd",
          name: "analytics-ussd",
          component: () => import("@/views/analytics/AnalyticsUssdView.vue"),
          meta: { title: "USSD Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/strongroom",
          name: "analytics-strongroom",
          component: () => import("@/views/analytics/AnalyticsStrongroomView.vue"),
          meta: { title: "Strongroom Analytics", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/historical",
          name: "analytics-historical",
          component: () => import("@/views/analytics/AnalyticsHistoricalView.vue"),
          meta: { title: "Historical Trends", roles: ["admin", "super_admin"] },
        },
        {
          path: "analytics/reports",
          name: "analytics-reports",
          component: () => import("@/views/analytics/AnalyticsReportsView.vue"),
          meta: { title: "Analytics Reports", roles: ["admin", "super_admin"] },
        },
      ],
    },
    {
      path: "/maintenance",
      component: PublicLayout,
      meta: { public: true },
      children: [
        {
          path: "",
          name: "maintenance",
          component: () => import("@/views/errors/MaintenanceView.vue"),
          meta: { title: "Maintenance", public: true },
        },
      ],
    },
    {
      path: "/verify",
      component: VerificationLayout,
      meta: { public: true },
      children: [
        {
          path: "",
          name: "verify-election",
          component: () => import("@/views/strongroom/VerificationCenterView.vue"),
          meta: { title: "Verification Center", public: true },
        },
      ],
    },
    {
      path: "/elections/:uuid",
      component: ElectionLayout,
      meta: { requiresAuth: true },
      children: [
        {
          path: "",
          name: "election-detail",
          component: () => import("@/views/elections/ElectionDetailView.vue"),
          meta: { title: "Election" },
        },
        {
          path: "vote",
          name: "election-vote",
          component: () => import("@/views/elections/VotingWizardView.vue"),
          meta: { title: "Vote", roles: ["student", "candidate"] },
        },
        {
          path: "confirmation",
          name: "election-confirmation",
          component: () => import("@/views/elections/VoteConfirmationView.vue"),
          meta: { title: "Vote Confirmation", roles: ["student", "candidate"] },
        },
      ],
    },
    {
      path: "/:pathMatch(.*)*",
      name: "not-found",
      component: () => import("@/views/NotFoundView.vue"),
      meta: { title: "Not Found" },
    },
  ],
  scrollBehavior() {
    return { top: 0 };
  },
});

export default router;
