# Generated by Django 5.2.15 on 2026-06-22 15:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0003_position_votereligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SVTToken',
            fields=[
                ('svt_id', models.UUIDField(db_column='svt_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_code', models.CharField(db_column='token_code', max_length=128, unique=True)),
                ('issued_at', models.DateTimeField(db_column='issued_at', default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('used_at', models.DateTimeField(blank=True, db_column='used_at', null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_column='status', db_index=True, default='issued', max_length=20)),
                ('election', models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.PROTECT, related_name='svt_tokens', to='elections.election')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='svt_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SVT token',
                'verbose_name_plural': 'SVT tokens',
                'db_table': 'svt_tokens',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['election', 'user', 'status'], name='svt_tokens_electio_2f5a9d_idx'), models.Index(fields=['expires_at'], name='svt_tokens_expires_2d8cf1_idx')],
            },
        ),
    ]
