# Generated by Django 5.2.15 on 2026-06-22 16:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_position_votereligibility'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('location_log_id', models.UUIDField(db_column='location_log_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(db_column='ip_address', unique=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=100)),
                ('region', models.CharField(blank=True, db_column='region', max_length=100)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=6, max_digits=9, null=True)),
                ('last_seen_at', models.DateTimeField(db_column='last_seen_at', db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'location_logs',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('device_log_id', models.UUIDField(db_column='device_log_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser_fingerprint', models.CharField(db_column='browser_fingerprint', db_index=True, max_length=128)),
                ('device_type', models.CharField(db_column='device_type', max_length=20)),
                ('operating_system', models.CharField(db_column='operating_system', max_length=50)),
                ('user_agent', models.TextField(db_column='user_agent')),
                ('last_seen_at', models.DateTimeField(db_column='last_seen_at', db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_logs',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.UUIDField(db_column='audit_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('mfa_required', 'MFA Required'), ('mfa_completed', 'MFA Completed'), ('session_revoked', 'Session Revoked'), ('token_refresh', 'Token Refresh'), ('election_accessed', 'Election Accessed'), ('election_created', 'Election Created'), ('election_updated', 'Election Updated'), ('election_deleted', 'Election Deleted'), ('election_status_changed', 'Election Status Changed'), ('ballot_viewed', 'Ballot Viewed'), ('vote_cast', 'Vote Cast'), ('vote_verified', 'Vote Verified'), ('vote_confirmation_viewed', 'Vote Confirmation Viewed'), ('svt_issued', 'SVT Issued'), ('svt_consumed', 'SVT Consumed'), ('svt_revoked', 'SVT Revoked'), ('svt_reissued', 'SVT Reissued'), ('svt_vote_verified', 'SVT Vote Verified'), ('admin_action', 'Admin Action')], db_column='event_type', db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ip_address', null=True)),
                ('user_agent', models.TextField(blank=True, db_column='user_agent')),
                ('metadata', models.JSONField(blank=True, db_column='metadata', default=dict)),
                ('timestamp', models.DateTimeField(db_column='timestamp', db_index=True, default=django.utils.timezone.now)),
                ('election', models.ForeignKey(blank=True, db_column='election_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='elections.election')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('device_log', models.ForeignKey(blank=True, db_column='device_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='security.devicelog')),
                ('location_log', models.ForeignKey(blank=True, db_column='location_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='security.locationlog')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='devicelog',
            index=models.Index(fields=['browser_fingerprint', 'user'], name='device_logs_browser_aab988_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'event_type'], name='audit_logs_user_id_b5ee1c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['election', 'event_type'], name='audit_logs_electio_666034_idx'),
        ),
    ]
