# Generated by Django 5.2.15 on 2026-06-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_locationlog_devicelog_auditlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('mfa_required', 'MFA Required'), ('mfa_completed', 'MFA Completed'), ('session_revoked', 'Session Revoked'), ('token_refresh', 'Token Refresh'), ('election_accessed', 'Election Accessed'), ('election_created', 'Election Created'), ('election_updated', 'Election Updated'), ('election_deleted', 'Election Deleted'), ('election_status_changed', 'Election Status Changed'), ('ballot_viewed', 'Ballot Viewed'), ('vote_cast', 'Vote Cast'), ('vote_verified', 'Vote Verified'), ('vote_confirmation_viewed', 'Vote Confirmation Viewed'), ('svt_issued', 'SVT Issued'), ('svt_validated', 'SVT Validated'), ('ballot_started', 'Ballot Started'), ('ballot_submitted', 'Ballot Submitted'), ('svt_consumed', 'SVT Consumed'), ('svt_revoked', 'SVT Revoked'), ('svt_reissued', 'SVT Reissued'), ('svt_vote_verified', 'SVT Vote Verified'), ('admin_action', 'Admin Action')], db_column='event_type', db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='svttoken',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('validated', 'Validated'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_column='status', db_index=True, default='issued', max_length=20),
        ),
    ]
