"""Real-time event type constants."""

ELECTION_OPENED = "election_opened"
ELECTION_CLOSED = "election_closed"
BALLOT_SUBMITTED = "ballot_submitted"
SVT_ISSUED = "svt_issued"
SVT_VALIDATED = "svt_validated"
SVT_CONSUMED = "svt_consumed"
SECURITY_ALERT_CREATED = "security_alert_created"
SECURITY_ALERT_RESOLVED = "security_alert_resolved"
FRAUD_CASE_CREATED = "fraud_case_created"
FRAUD_CASE_RESOLVED = "fraud_case_resolved"
FRAUD_CASE_ESCALATED = "fraud_case_escalated"
RESULTS_GENERATED = "results_generated"
RESULTS_CERTIFIED = "results_certified"
RESULTS_PUBLISHED = "results_published"
STRONGROOM_SEALED = "strongroom_sealed"
STRONGROOM_VERIFIED = "strongroom_verified"
ELECTION_LOCKED = "election_locked"
INTEGRITY_CHECK_COMPLETED = "integrity_check_completed"
DASHBOARD_STATS = "dashboard_stats"
COMMUNICATION_DELIVERY_UPDATED = "communication_delivery_updated"
IN_APP_NOTIFICATION_CREATED = "in_app_notification_created"
USSD_SESSION_UPDATED = "ussd_session_updated"
USSD_VOTE_COMPLETED = "ussd_vote_completed"
LIVE_TREND_UPDATED = "live_trend_updated"
