# Generated by Django 5.2.15 on 2026-06-21 22:25

import apps.candidates.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('manifesto', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.candidates.models.candidate_image_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
            ],
            options={
                'verbose_name': 'candidate',
                'verbose_name_plural': 'candidates',
                'db_table': 'candidates_candidate',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['election', 'status'], name='candidates__electio_63444a_idx')],
                'constraints': [models.UniqueConstraint(fields=('election', 'full_name'), name='candidates_unique_name_per_election')],
            },
        ),
    ]
