# Generated by Django 5.2.15 on 2026-06-21 21:50

import apps.accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='MFALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('mfa_required', 'MFA Required'), ('mfa_completed', 'MFA Completed'), ('logout', 'Logout'), ('session_revoked', 'Session Revoked'), ('token_refresh', 'Token Refresh')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mfa_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_mfa_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='accounts_mf_user_id_65acc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('mfa', 'Multi-Factor Authentication')], max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_otp_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_verified'], name='accounts_ot_user_id_f77737_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_af93f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('refresh_token_jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_se_user_id_a7a6eb_idx')],
            },
        ),
    ]
