# Generated by Django 5.2.15 on 2026-06-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auth_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfalog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Failed'), ('mfa_required', 'MFA Required'), ('mfa_completed', 'MFA Completed'), ('logout', 'Logout'), ('session_revoked', 'Session Revoked'), ('token_refresh', 'Token Refresh'), ('ballot_viewed', 'Ballot Viewed'), ('vote_cast', 'Vote Cast'), ('vote_verified', 'Vote Verified'), ('vote_confirmation_viewed', 'Vote Confirmation Viewed'), ('svt_issued', 'SVT Issued'), ('svt_validated', 'SVT Validated'), ('ballot_started', 'Ballot Started'), ('ballot_submitted', 'Ballot Submitted'), ('svt_consumed', 'SVT Consumed'), ('svt_revoked', 'SVT Revoked'), ('svt_reissued', 'SVT Reissued'), ('svt_vote_verified', 'SVT Vote Verified')], db_index=True, max_length=30),
        ),
    ]
