# Generated by Django 5.2.15 on 2026-06-22 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0002_alter_candidate_position_and_more'),
        ('elections', '0003_position_votereligibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(db_column='vote_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('svt_id', models.UUIDField(blank=True, db_column='svt_id', help_text='Strongroom verification token — populated in Phase 5.', null=True)),
                ('vote_hash', models.CharField(db_column='vote_hash', max_length=128)),
                ('timestamp', models.DateTimeField(db_column='timestamp', default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='candidates.candidate')),
                ('channel', models.ForeignKey(db_column='channel_id', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='elections.votingchannel')),
                ('election', models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='elections.election')),
                ('position', models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='elections.position')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'db_table': 'voting_vote',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['election', 'user'], name='voting_vote_electio_b3e19a_idx'), models.Index(fields=['position', 'user'], name='voting_vote_positio_882145_idx'), models.Index(fields=['vote_hash'], name='voting_vote_vote_ha_21bb5d_idx'), models.Index(fields=['timestamp'], name='voting_vote_timesta_1e3967_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'position', 'candidate'), name='voting_unique_user_position_candidate')],
            },
        ),
    ]
