# Generated by Django 5.2.15 on 2026-07-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trusted_devices', '0003_identity_trust_framework'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='trusted_dev_user_id_f21622_idx',
            old_name='trusted_dev_user_id_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='trusteddevice',
            new_name='trusted_dev_user_id_7bdbc7_idx',
            old_name='trusted_dev_user_id_9d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='trusteddeviceloginhistory',
            new_name='trusted_dev_device__2fb485_idx',
            old_name='td_login_dev_time_idx',
        ),
        migrations.RenameIndex(
            model_name='trusteddeviceloginhistory',
            new_name='trusted_dev_user_id_ee9e88_idx',
            old_name='td_login_user_time_idx',
        ),
    ]
