# Generated by Django 5.2.15 on 2026-06-21 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('channel_name', models.CharField(choices=[('web', 'Web'), ('ussd', 'USSD'), ('sms', 'SMS')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'voting channel',
                'verbose_name_plural': 'voting channels',
                'db_table': 'elections_voting_channel',
                'ordering': ['channel_name'],
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('election_type', models.CharField(choices=[('general', 'General'), ('student_union', 'Student Union'), ('faculty', 'Faculty'), ('departmental', 'Departmental'), ('special', 'Special')], max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('allow_web_voting', models.BooleanField(default=True)),
                ('allow_ussd_voting', models.BooleanField(default=False)),
                ('allow_sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'election',
                'verbose_name_plural': 'elections',
                'db_table': 'elections_election',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='elections_e_status_2b6bdc_idx')],
            },
        ),
    ]
