# Generated by Django 5.2.15 on 2026-06-22 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_seed_voting_channels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('max_votes_allowed', models.PositiveSmallIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='elections.election')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'db_table': 'elections_position',
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['election', 'is_active'], name='elections_p_electio_16d002_idx')],
                'constraints': [models.UniqueConstraint(fields=('election', 'title'), name='elections_unique_position_title_per_election')],
            },
        ),
        migrations.CreateModel(
            name='VoterEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_eligible', models.BooleanField(db_index=True, default=True)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_eligibilities', to='elections.election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_eligibilities', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voter eligibility',
                'verbose_name_plural': 'voter eligibilities',
                'db_table': 'elections_voter_eligibility',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election', 'is_eligible'], name='elections_v_electio_1b6668_idx')],
                'constraints': [models.UniqueConstraint(fields=('election', 'user'), name='elections_unique_voter_per_election')],
            },
        ),
    ]
