"""USSD flow step constants."""

WELCOME = "WELCOME"
MAIN_MENU = "MAIN_MENU"
AUTH_INDEX = "AUTH_INDEX"
AUTH_PIN = "AUTH_PIN"
VOTE_LIST = "VOTE_LIST"
VOTE_SELECT = "VOTE_SELECT"
VOTE_POSITION = "VOTE_POSITION"
VOTE_CANDIDATE = "VOTE_CANDIDATE"
VOTE_REVIEW = "VOTE_REVIEW"
VOTE_CONFIRM = "VOTE_CONFIRM"
STATUS_LIST = "STATUS_LIST"
VERIFY_SVT = "VERIFY_SVT"
INFO_LIST = "INFO_LIST"
INFO_DETAIL = "INFO_DETAIL"
HELP = "HELP"

MENU_TARGETS = {
    "1": VOTE_LIST,
    "2": STATUS_LIST,
    "3": VERIFY_SVT,
    "4": INFO_LIST,
    "5": HELP,
    "6": None,  # exit
}
