# Generated by Django 5.2.15 on 2026-06-22 16:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('alert_id', models.UUIDField(db_column='alert_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('duplicate_device', 'Duplicate Device'), ('duplicate_location', 'Duplicate Location'), ('excessive_login_attempts', 'Excessive Login Attempts'), ('excessive_svt_requests', 'Excessive SVT Requests'), ('suspicious_voting_pattern', 'Suspicious Voting Pattern'), ('multiple_accounts_same_device', 'Multiple Accounts Same Device')], db_column='alert_type', db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], db_column='status', db_index=True, default='open', max_length=20)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('description', models.TextField(db_column='description')),
                ('metadata', models.JSONField(blank=True, db_column='metadata', default=dict)),
                ('created_at', models.DateTimeField(db_column='created_at', db_index=True, default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_column='resolved_at', null=True)),
                ('escalated_at', models.DateTimeField(blank=True, db_column='escalated_at', null=True)),
            ],
            options={
                'db_table': 'security_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
