# Generated by Django 5.2.15 on 2026-06-22 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0003_position_votereligibility'),
        ('fraud', '0001_initial'),
        ('security', '0002_locationlog_devicelog_auditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='device_log',
            field=models.ForeignKey(blank=True, db_column='device_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='security.devicelog'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='election',
            field=models.ForeignKey(blank=True, db_column='election_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='elections.election'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='escalated_by',
            field=models.ForeignKey(blank=True, db_column='escalated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='location_log',
            field=models.ForeignKey(blank=True, db_column='location_log_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='security.locationlog'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_column='resolved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['alert_type', 'status'], name='security_al_alert_t_60f9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['election', 'status'], name='security_al_electio_f4eb59_idx'),
        ),
    ]
