# Generated by Django 5.2.15 on 2026-06-22 17:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_position_votereligibility'),
        ('fraud', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('fraud_case_id', models.UUIDField(db_column='fraud_case_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.PositiveSmallIntegerField(db_column='risk_score', default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_column='severity', db_index=True, default='low', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], db_column='status', db_index=True, default='open', max_length=20)),
                ('investigation_notes', models.TextField(blank=True, db_column='investigation_notes')),
                ('created_at', models.DateTimeField(db_column='created_at', db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('election', models.ForeignKey(blank=True, db_column='election_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_cases', to='elections.election')),
                ('related_alert', models.ForeignKey(db_column='related_alert_id', on_delete=django.db.models.deletion.PROTECT, related_name='fraud_cases', to='fraud.securityalert')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election', 'status'], name='fraud_cases_electio_7d34c0_idx'), models.Index(fields=['severity', 'status'], name='fraud_cases_severit_7f3eb3_idx')],
                'constraints': [models.UniqueConstraint(fields=('related_alert',), name='fraud_unique_case_per_alert')],
            },
        ),
    ]
