# Generated by Django 5.2.15 on 2026-07-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_seed_identity_assurance_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='biometricverificationlog',
            new_name='biometrics__user_id_7381ed_idx',
            old_name='biometrics__user_id_6a0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricverificationlog',
            new_name='biometrics__created_aaf21f_idx',
            old_name='biometrics__created_8f2c1a_idx',
        ),
    ]
